import Head from "next/head";
import Btn from "../../components/Btn";
import Link from "next/link";
import Image from "next/image";
import { useEffect } from "react";
import { useTranslation } from "react-i18next";
import { useSelector } from "react-redux";
import { useRouter } from "next/router";
import { selectFromData } from "../../redux/features/mobileInputs/formDataSlice";

const Download = () => {
  const { t, i18n } = useTranslation();
  const { discountTmpId } = useSelector(selectFromData);
  const router = useRouter();

  useEffect(() => {
    if (discountTmpId === "") {
      router.push("/signup/step-1");
    }
  }, []);

  return (
    <div className="min-h-screen bg-gradient-to-b from-[#08115d] to-[#95bf5c]  items-center grid grid-cols-1 place-content-center">
      <Head>
        <title>Discount Create | Download</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center ">
        <div className="">
          <div className="flex justify-center pb-8 pt-2">
            <img className="logo" src="/pikoo-logo.png" />
          </div>

          <div className="max-w-md w-[28rem] bg-white rounded-lg  shadow-md mb-4">
            <h5 className="text-base p-3 font-medium text-gray-900 bg-[#c5f177] text-center rounded-tl-lg rounded-tr-lg shadow-md">
              {`Дисконтная программа создана`}
            </h5>

            <div className="sm:pt-0 px-4 sm:px-10 ">
              <form className="pt-4" action="#">
                <p className="font-bold text-center text-xs">{`Для каждой из Ваших 
                                точек продаж созданы QR-коды.
                                Разместите их в прикассовой зоне для сканирования клиентами`}</p>

                <div className="flex justify-center items-center pt-4 ">
                  <Image
                    className=""
                    height={100}
                    width={100}
                    src="/../public/zip-file.png "
                    alt="img"
                  />
                </div>
                <div>
                  <p className="p-1 text-center">Скачать ZIP - архив</p>
                </div>
                <div className="flex justify-center items-center ">
                  <div className=" px-4 py-2 shadow-lg hover:shadow-md cursor-pointer rounded-md">
                    <Image
                      className="cursor-pointer"
                      height={20}
                      width={20}
                      src="/../public/down-arrow.png"
                      alt="img"
                    />
                  </div>
                </div>
                <div className=" sm:px-8 pb-6 items-center text-center mt-4">
                  <Link href="/dashboard">
                    <a>
                      <Btn innertext={`Закрыть`} />
                    </a>
                  </Link>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Download;
