import Head from "next/head";
import Image from "next/image";
import { useTranslation } from "react-i18next";
import { useEffect } from "react";
import { ChangeEvent, useState } from "react";
import MobileInput from "../../components/MobileInput";
import Mobile from "../../components/Mobile";
import Checkbox from "../../components/Checkbox";
import Link from "next/link";
import Btn from "../../components/Btn";
import { useFormik } from "formik";
import * as yup from "yup";
import { useDispatch, useSelector } from "react-redux";
import { useRouter } from "next/router";
import client from "../../utils/client";
import {
  selectInputState,
  setInputState,
} from "../../redux/features/mobileInputs/mobileInputSlice";
import { selectFromData } from "../../redux/features/mobileInputs/formDataSlice";

const Step1 = () => {
  const dispatch = useDispatch();
  const { t, i18n } = useTranslation();
  const [domLoaded, setDomLoaded] = useState(false);
  const [message, setmessage] = useState("");
  const { discountTmpId } = useSelector(selectFromData);
  const { inputs } = useSelector(selectInputState);
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  // const [token, setToken] = useState("");

  // useEffect(() => {
  //   if (typeof window !== "undefined") {
  //     const mytoken = localStorage.getItem("token");
  //     if (mytoken) {
  //       setToken(mytoken);
  //     }
  //   }
  //   return () => {};
  // }, []);

  const discountCreateStep = (formData: any) => {
    setLoading(true);
    if (formData.fields.length > 2) {
      client
        .post(
          "/api/v1/discount/step",
          {
            discountTmpId,
            step: "DISCOUNT_CREATION_STEP_REGISTRATION_FORM",
            registrationForm: {
              registrationForm: formData,
            },
          },
          {
            headers: { 'Authorization' : `Bearer ${localStorage.getItem("token")}` },
          }
        )
        .then((res: any) => {
          if (res.status === 200) {
            router.push("/discount-create/step-2");
          }
        })
        .catch((err: any) => {
          setLoading(false);
          console.log(err);
        });
    } else {
      setmessage("Please select field more than 2 ");
    }
  };

  useEffect(() => {
    setDomLoaded(true);
    if (discountTmpId === "") {
      router.push("/signup/step-1");
    }
  }, []);

  const CheckTheBox = (e: ChangeEvent) => {
    dispatch(setInputState(e.target.id));
  };

  const loginSchema = yup.object().shape({});
  // yup schema

  const formik = useFormik({
    initialValues: {},
    onSubmit: (values) => {
      // alert(JSON.stringify(values, null, 2));
      discountCreateStep(values);
    },
    validationSchema: loginSchema,
  });
  return (
    <div className="min-h-screen bg-gradient-to-b from-[#08115d] to-[#95bf5c]  items-center grid grid-cols-1 place-content-center">
      <Head>
        <title>Discount Create | Step 1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center ">
        <div>
          <div className="flex justify-center pb-8 pt-2">
            <img className="logo" src="/pikoo-logo.png" />
          </div>

          <div className=" Имяmy-4 pb-4 bg-gray-100 rounded-lg  shadow-md">
            <div className="absolute p-4 ">
              {" "}
              <Link href="/signup/step-3">
                <a>
                  <Image
                    className="cursor-pointer"
                    height={15}
                    width={15}
                    src="/../public/backarrow.png"
                    alt="asdf"
                  />
                </a>
              </Link>
            </div>
            <h5 className="text-base px-8 py-3 font-medium text-gray-900 bg-[#c5f177] text-center rounded-tl-lg rounded-tr-lg shadow-md">
              Настройка формы регистрации клиента
              <p className="text-xs">Шаг 1 из 2</p>
            </h5>

            <div className="sm:pt-0 sm:px-10 md:px-16 mb-0  ">
              <p className="p-4 m-0 text-xs text-center">
                Отметьте поля которые будут предложены клиентам при регистрации
              </p>
              <p className=" mt-2 text-xs font-bold px-4">Полный список </p>
              <form onSubmit={formik.handleSubmit} method="post">
                <div className="grid grid-cols-1 gap-2 md:grid-cols-2 ">
                  <div className=" rounded-lg bg-white p-4 my-4 shadow-lg mx-6 ">
                    <div className="flex flex-col gap-2">
                      {inputs.map((input: any, index: any) => (
                        <div key={input.id}>
                          <Checkbox
                            type="checkbox"
                            name="fields"
                            text={input.text}
                            value={input.id}
                            id={input.id}
                            ischecked={`${input.isChecked}`}
                            // onChange={CheckTheBox}
                            onChange={(e: any) => {
                              CheckTheBox(e);
                              formik.handleChange(e);
                            }}
                          />
                        </div>
                      ))}
                    </div>
                  </div>
                  <div className="">
                    {domLoaded && (
                      <Mobile>
                        {inputs.map((input: any, index: any) => (
                          <div key={index}>
                            {input.isChecked ? (
                              <MobileInput
                                label={input.text}
                                placeholder={input.text}
                                type={input.type}
                              />
                            ) : (
                              ""
                            )}
                          </div>
                        ))}
                      </Mobile>
                    )}
                  </div>
                  <p className="text-center text-sm">
                    {message ? message : ""}
                  </p>
                  <div className="flex justify-center">
                    {loading ? (
                      <div role="status" className="flex justify-center">
                        <svg
                          aria-hidden="true"
                          className="mr-2 w-6 h-6 text-gray-200 animate-spin dark:text-gray-600 fill-blue-600"
                          viewBox="0 0 100 101"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z"
                            fill="currentColor"
                          ></path>
                          <path
                            d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z"
                            fill="currentFill"
                          ></path>
                        </svg>
                        <span className="">Processing...</span>
                      </div>
                    ) : (
                      <Btn type="submit" innertext={`${t("common:next")}`} />
                    )}
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Step1;
