import Head from "next/head";
import Image from "next/image";
import { useTranslation } from "react-i18next";
import { useState, ChangeEvent } from "react";
import { useEffect } from "react";
import Link from "next/link";
import Btn from "../../components/Btn";
import { useRouter } from "next/router";
import { useSelector } from "react-redux";
import { selectFromData } from "../../redux/features/mobileInputs/formDataSlice";

const Step3 = () => {
  const { t, i18n } = useTranslation();
  const [domLoaded, setDomLoaded] = useState(false);
  const { discountTmpId } = useSelector(selectFromData);
  const router = useRouter();

  useEffect(() => {
    setDomLoaded(true);
    if (discountTmpId === "") {
      router.push("/signup/step-1");
    }
  }, []);

  const [checkboxs, setCheckBoxes] = useState([
    { label: "Действие 1", id: "first", checked: false },
    { label: "Действие 2", id: "second", checked: false },
    { label: "Действие 3", id: "third", checked: false },
    { label: "Действие 4", id: "fourth", checked: false },
    { label: "Действие 5", id: "fifth", checked: false },
    { label: "Действие 6", id: "sixth", checked: false },
    { label: "Действие 7", id: "seventh", checked: false },
    { label: "Действие 8", id: "eighth", checked: false },
  ]);

  const CheckTheBox = (e: ChangeEvent) => {
    // console.log(e.target);

    const newinputs = checkboxs.map((checkbox: any) => {
      if (checkbox.id === e.target.id) {
        checkbox.checked = !checkbox.checked;
      }
      return checkbox;
    });
    setCheckBoxes(newinputs);
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-[#08115d] to-[#95bf5c]  items-center grid grid-cols-1 place-content-center">
      <Head>
        <title>Discount Create | Step 3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center ">
        <div>
          <div className="flex justify-center pb-8 pt-2">
            <img className="logo" src="/pikoo-logo.png" />
          </div>

          <div className=" my-4  bg-gray-100 rounded-lg  shadow-md">
            <div className="absolute p-4 ">
              {" "}
              <Link href="step-2">
                <a>
                  <Image
                    className="cursor-pointer"
                    height={15}
                    width={15}
                    src="/../public/backarrow.png"
                    alt="asdf"
                  />
                </a>
              </Link>
            </div>
            <h5 className="text-base px-8 py-3 font-medium text-gray-900 bg-[#c5f177] text-center rounded-tl-lg rounded-tr-lg shadow-md">
              Создаем учетную запись…
            </h5>

            <div className="sm:pt-0  sm:px-4 md:px-18 mb-0  ">
              <form className="pt-4" action="#">
                <div className="md:flex pb-4">
                  <div className="flex justify-center items-center">
                    <div className=" ">
                      <div className="grid grid-cols-2 sm:grid-cols-4   gap-2 p-4">
                        {checkboxs.map((checkbox, index, key) => (
                          <div key={index}>
                            <label
                              className={`flex justify-center items-center w-full  rounded-md shadow  ${
                                checkbox.checked
                                  ? "bg-[#c5f177]"
                                  : "bg-gray-200"
                              }  cursor-pointer w-32 h-32 pt-0" `}
                              htmlFor={checkbox.label}
                            >
                              <div className=" mb-6">
                                <p className=" text-center pb-4">
                                  {checkbox.label}
                                </p>
                                <div className="flex justify-center">
                                  <span
                                    className={`flex justify-center  border-2 rounded p-1   items-center ${
                                      checkbox.checked ? " border-black " : ""
                                    } `}
                                  >
                                    {checkbox.checked ? (
                                      <Image
                                        className=""
                                        height={20}
                                        width={20}
                                        src="/../public/check-mark.png"
                                        alt="asdf"
                                      />
                                    ) : (
                                      <Image
                                        className=""
                                        height={20}
                                        width={20}
                                        src="/../public/forward-arrow.png"
                                        alt="asdf"
                                      />
                                    )}
                                  </span>
                                </div>
                              </div>
                            </label>
                            <input
                              className="hidden"
                              id={checkbox.id}
                              type="checkbox"
                              onChange={CheckTheBox}
                            />
                          </div>
                        ))}
                      </div>
                      <div className="flex justify-center">
                        <Link href="/sale-points">
                          <a>
                            <Btn innertext={`${t("common:next")}`} />
                          </a>
                        </Link>
                      </div>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Step3;
