import Head from "next/head";
import { useTranslation } from "react-i18next";
import Inputfield from "../../components/Inputfield";
import Btn from "../../components/Btn";
import DropDown from "../../components/Dropdown";
import { useFormik } from "formik";
import * as yup from "yup";
import { useDispatch } from "react-redux";
import {
  setCompanyName,
  setplatformCountry,
  setplatform,
} from "../../redux/features/mobileInputs/formDataSlice";
import { useRouter } from "next/router";

const Step1 = () => {
  const { t, i18n } = useTranslation();
  const router = useRouter();
  const dispatch = useDispatch();

  const step1Schema = yup.object().shape({
    name: yup.string().required("Enter Your Company Name"),
    platform: yup.string().required("select platform"),
    platformCountry: yup.string().required("select platformCountry"),
  });
  // yup schema

  const formik = useFormik({
    initialValues: {
      name: ``,
      platform: ``,
      platformCountry: ``,
    },
    onSubmit: (values) => {
      dispatch(setCompanyName(values.name));
      dispatch(setplatform(values.platform));
      dispatch(setplatformCountry(values.platformCountry));
      router.push("/signup/step-2");
      //   alert(JSON.stringify(values, null, 2));
    },
    validationSchema: step1Schema,
  });

  return (
    <div className="min-h-screen bg-gradient-to-b from-[#08115d] to-[#95bf5c]  items-center grid grid-cols-1 place-content-center">
      <Head>
        <title>Step 1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center ">
        <div className="">
          <div className="flex justify-center pb-8 pt-2">
            <img className="logo" src="/pikoo-logo.png" />
          </div>

          <div className="max-w-md w-full sm:w-96 bg-white rounded-lg  shadow-md ">
            <h5 className="text-base p-3 font-medium text-gray-900 bg-[#c5f177] text-center rounded-tl-lg rounded-tr-lg shadow-md">
              {`${t("common:creatediscountprogram")}`}
              <p className="text-xs">
                {`${t("common:step")}`} 1 {`${t("common:of")}`} 3{" "}
              </p>
            </h5>

            <div className="sm:pt-0 px-10 sm:px-10 md:px-8">
              <form onSubmit={formik.handleSubmit} method="post">
                <p className="font-bold p-0 m-0 text-xs pt-2">
                  Название Вашей дисконтной программы{" "}
                </p>
                <p className="text-xs p-0 m-0">{`${t(
                  "common:discountdec"
                )}`}</p>
                <div className="pt-2">
                  <div className="my-2">
                    <label
                      htmlFor="platform"
                      className="block mb-1 text-xs font-medium text-gray-500"
                    >
                      Select Platform
                    </label>
                    <select
                      className="rounded-md border border-gray-300 text-gray-900 text-sm focus:ring-blue-500 focus:border-blue-500 block w-full p-1 "
                      name="platform"
                      onChange={formik.handleChange}
                      value={formik.values.platform}
                    >
                      <option value="platform1">platform1</option>
                      <option value="platform2">platform2</option>
                      <option value="platform3">platform3</option>
                    </select>
                  </div>
                  <p className="block text-xs font-medium text-red-600">
                    {formik.errors.platform && formik.touched.platform && (
                      <div className="block h-2 text-xs font-medium text-red-600">
                        {formik.errors.platform}
                      </div>
                    )}
                  </p>
                </div>
                <div className="pt-2">
                  <div className="my-2">
                    <label
                      htmlFor="platformCountry"
                      className="block mb-1 text-xs font-medium text-gray-500"
                    >
                      Select Platform Country
                    </label>
                    <select
                      className="rounded-md border border-gray-300 text-gray-900 text-sm focus:ring-blue-500 focus:border-blue-500 block w-full p-1 "
                      name="platformCountry"
                      onChange={formik.handleChange}
                      value={formik.values.platformCountry}
                    >
                      <option value="platformCountry1">platformCountry1</option>
                      <option value="platformCountry2">platformCountry2</option>
                      <option value="platformCountry3">platformCountry3</option>
                    </select>
                  </div>
                  <p className="block text-xs font-medium text-red-600">
                    {formik.errors.platformCountry &&
                      formik.touched.platformCountry && (
                        <div className="block h-2 text-xs font-medium text-red-600">
                          {formik.errors.platformCountry}
                        </div>
                      )}
                  </p>
                </div>
                <div className="mb-8">
                  <div className="mt-4">
                    <label
                      htmlFor="platformCountry"
                      className="block mb-1 text-xs font-medium text-gray-500"
                    >
                      Company Name
                    </label>
                    <Inputfield
                      label={""}
                      htmlFor={"name"}
                      name={"name"}
                      id={"name"}
                      inputtype={"text"}
                      placeholder="Coffetogo"
                      onChange={formik.handleChange}
                      value={formik.values.name}
                    />
                  </div>
                  <p className="block text-xs font-medium text-red-600">
                    {formik.errors.name && formik.touched.name && (
                      <div className="block text-xs font-medium text-red-600">
                        {formik.errors.name}
                      </div>
                    )}
                  </p>
                </div>

                <div className=" sm:px-8 pb-6 items-center text-center">
                  <Btn type="submit" innertext={`${t("common:next")}`} />
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Step1;
