import React, { useState } from 'react'
import Head from "next/head"
import SecondaryBtn from '../components/SecondaryBtn';
import PrimaryBtn from '../components/PrimaryBtn';
import TriangleBtn from '../components/TriangleBtn';
import DashboardSidebar from '../components/DashboardSidebar';
import Chart from '../components/Chart';
import DashboardHeader from '../components/DashboardHeader';
import DateInput from '../components/DateInput';
import "flatpickr/dist/themes/material_green.css";
import { useTranslation } from "react-i18next"
// import Flatpickr from "react-flatpickr";

export default function Dashboard(props: any) {
    const { t, i18n } = useTranslation();

    const [startDate, setStartDate] = useState(new Date());
    const data = [
        {
            name: `${t("dashboard:January")}`,
            uv: 0,
        },

        {
            name: `${t("dashboard:February")}`,
            uv: 1100,
        },
        {
            name: `${t("dashboard:March")}`,
            uv: 1200,
        },
        {
            name: `${t("dashboard:April")}`,
            uv: 2000,
        },
        {
            name: `${t("dashboard:May")}`,
            uv: 3000,
        },
        {
            name: `${t("dashboard:June")}`,
            uv: 4000,
        },
        {
            name: `${t("dashboard:July")}`,
            uv: 5000,
        },
        {
            name: `${t("dashboard:August")}`,
            uv: 6000,
        },
        {
            name: `${t("dashboard:September")}`,
            uv: 7000,
        },
        {
            name: `${t("dashboard:October")}`,
            uv: 8000,
        },
        {
            name: `${t("dashboard:November")}`,
            uv: 9000,
        },
        {
            name: `${t("dashboard:December")}`,
            uv: 10000,
        },


    ];
    const data2 = [
        {
            name: `${t("dashboard:January")}`,
            uv: 0,
        },

        {
            name: `${t("dashboard:February")}`,
            uv: 1100,
        },
        {
            name: `${t("dashboard:March")}`,
            uv: 1200,
        },
        {
            name: `${t("dashboard:April")}`,
            uv: 2000,
        },
        {
            name: `${t("dashboard:May")}`,
            uv: 3000,
        },
        {
            name: `${t("dashboard:June")}`,
            uv: 4000,
        },
        {
            name: `${t("dashboard:July")}`,
            uv: 5000,
        },
        {
            name: `${t("dashboard:August")}`,
            uv: 6000,
        },
        {
            name: `${t("dashboard:September")}`,
            uv: 7000,
        },
        {
            name: `${t("dashboard:October")}`,
            uv: 8000,
        },
        {
            name: `${t("dashboard:November")}`,
            uv: 9000,
        },
        {
            name: `${t("dashboard:December")}`,
            uv: 10000,
        },


    ];

    return (
        <div className=" h-full">
            <Head>
                <title>Dashboard</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex flex-no-wrap w-full">
                <DashboardSidebar />


                <div className=" bg-gray-50 w-[100%] sm:w-[80%]">
                    <DashboardHeader />
                    <div className='px-10 py-6'>
                        <div className="flex justify-between">
                            <div className='flex items-center'><p className="font-bold">{`${t("dashboard:Statistics")}`}</p> 
                               
                            </div>
                            <div className='flex'>
                                <div className="px-2 flex items-center"><p className="font-bold">{`${t("dashboard:Available")}`}3/3</p></div>
                                <PrimaryBtn>{`${t("dashboard:Buyacard")}`}</PrimaryBtn>
                            </div>
                        </div>
                    </div>
                    <div className=' px-10 '>
                        <div className=" h-full  rounded mb-8">
                            <div className=' container h-full bg-white rounded shadow-md'>
                                <div className="bg-[#c5f177] py-4 px-5 rounded-t-md"><p className="font-bold">{`${t("dashboard:General")}`}</p></div>
                                <div className="py-4 px-5 flex justify-between">
                                    <div className="flex">
                                        <div className="mr-2">
                                            <SecondaryBtn>
                                                <div className="flex items-center justify-between text-xs">
                                                    {`${t("dashboard:Newcards")}`}
                                                    <TriangleBtn />
                                                </div>
                                            </SecondaryBtn>
                                        </div>
                                        <div className="mr-2">
                                            <SecondaryBtn>
                                                <div className="flex items-center justify-between text-xs">
                                                    {`${t("dashboard:Aweek")}`}
                                                    <TriangleBtn />
                                                </div>

                                            </SecondaryBtn>
                                        </div>
                                        <div className="mr-2">
                                            <SecondaryBtn>
                                                <div className="flex items-center justify-between text-xs">
                                                    
                                                    {`${t("dashboard:Month")}`}
                                                    <TriangleBtn />
                                                </div>

                                            </SecondaryBtn>
                                        </div>
                                        <div className="mr-2 ">
                                            <PrimaryBtn>
                                                <div className="flex items-center justify-between text-xs">
                                                    {`${t("dashboard:Quarter")}`}
                                                    <TriangleBtn />
                                                </div>

                                            </PrimaryBtn>
                                        </div>
                                        <div className="mr-2">
                                            <SecondaryBtn>
                                                <div className="flex items-center justify-between text-xs">
                                                    {`${t("dashboard:Year")}`}
                                                    <TriangleBtn />
                                                </div>

                                            </SecondaryBtn>
                                        </div>
                                    </div>
                                    <div className="flex">
                                        <div className="mr-2 flex items-center">
                                            <p className="text-xs mr-1">{`${t("dashboard:datefrom")}`}</p>
                                            <DateInput defaultValue={t("dashboard:datefrom")} />

                                        </div>
                                        <div className="mr-2 flex items-center">
                                            <p className="text-xs mr-1">{`${t("dashboard:Dateto")}`}</p>
                                            <DateInput defaultValue={'Дата до'} />
                                        </div>
                                    </div>
                                </div>
                                <div className="w-full h-[330px] px-2">
                                    <Chart data={data}></Chart>
                                </div>
                            </div>

                        </div>
                        <div className=" h-full  rounded mb-8">
                            <div className=' container h-full bg-white rounded shadow-md'>
                                <div className="bg-[#c5f177] py-4 px-5 rounded-t-md"><p className="font-bold">{`${t("dashboard:Bypoints")}`}</p></div>
                                <div className="py-4 px-5 flex justify-between">
                                    <div className="flex">
                                        <div className="mr-2">
                                            <SecondaryBtn>
                                                <div className="flex items-center justify-between text-xs">
                                                    {`${t("dashboard:Newcards")}`}
                                                    <TriangleBtn />
                                                </div>
                                            </SecondaryBtn>
                                        </div>
                                        <div className="mr-2">
                                            <SecondaryBtn>
                                                <div className="flex items-center justify-between text-xs">
                                                    {`${t("dashboard:Pointsofsale")}`}
                                                    <TriangleBtn />
                                                </div>
                                            </SecondaryBtn>
                                        </div>
                                        <div className="mr-2">
                                            <SecondaryBtn>
                                                <div className="flex items-center justify-between text-xs">
                                                    {`${t("dashboard:Aweek")}`}
                                                    <TriangleBtn />
                                                </div>
                                            </SecondaryBtn>
                                        </div>
                                        <div className="mr-2">
                                            <SecondaryBtn>
                                                <div className="flex items-center justify-between text-xs">
                                                    {`${t("dashboard:Month")}`}
                                                    <TriangleBtn />
                                                </div>
                                            </SecondaryBtn>
                                        </div>
                                        <div className="mr-2 "><PrimaryBtn>   {`${t("dashboard:Quarter")}`}  <TriangleBtn /></PrimaryBtn></div>
                                        <div className="mr-2">
                                            <SecondaryBtn>
                                                <div className="flex items-center justify-between text-xs">
                                                {`${t("dashboard:Year")}`}
                                                    <TriangleBtn />
                                                </div>
                                            </SecondaryBtn>
                                        </div>
                                    </div>
                                    <div className="flex">
                                        <div className="mr-2 flex items-center">
                                            <p className="text-xs mr-1"> {`${t("dashboard:datefrom")}`}</p>
                                            <DateInput defaultValue={t("dashboard:datefrom")} />

                                        </div>
                                        <div className="mr-2 flex items-center">
                                            <p className="text-xs mr-1">{`${t("dashboard:Dateto")}`}</p>
                                            <DateInput defaultValue={t("dashboard:Dateto")}/>
                                        </div>
                                    </div>
                                </div>
                                <div className=" w-full h-[330px] px-2">
                                    <Chart data={data2}></Chart>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

            </div>
        </div>
    )
}
