import type { NextPage } from "next";
import Head from "next/head";
import Inputfield from "../components/Inputfield";
import Btn from "../components/Btn";
import Link from "next/link";
import LanDropdown from "../components/LanDropdown";
import { useTranslation } from "react-i18next";
import { useFormik } from "formik";
import * as yup from "yup";
import client from "../utils/client";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

const Login: NextPage = () => {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [message, setmessage] = useState("");
  const loginUser = (email: string, pass: string) => {
    client
      .post("/api/v1/auth/login", {
        login: email,
        pass,
      })
      .then((res: any) => {
        // console.log(res);
        if (res.data.access_token) {
          localStorage.setItem("token", `${res.data.access_token}`);
          router.push("/dashboard");
        }
        if (res.status === 500) {
          setLoading(false);
          setmessage("Invalid Email Or Password ");
        }
      })
      .catch((err) => {
        if (err.code === "ERR_NETWORK") {
          setmessage("Network Error");
        }
        setLoading(false);
        console.log(err);
      });
  };

  const loginSchema = yup.object().shape({
    email: yup.string().email().required("Enter Your Email"),
    password: yup
      .string()
      .required("Enter Your Password")
      .min(6, "Must be 6 charaters")
      .max(30, "Must be 30 charaters"),
  });
  // yup schema

  const formik = useFormik({
    initialValues: {
      email: ``,
      password: ``,
    },
    onSubmit: (values) => {
      // alert(JSON.stringify(values, null, 2));
      setLoading(true);
      loginUser(values.email, values.password);
    },
    validationSchema: loginSchema,
  });
  const { t, i18n } = useTranslation();

  useEffect(() => {
    if (typeof window !== "undefined") {
      const token = localStorage.getItem("token");
      {
        token ? (
          router.push('/dashboard')
          ) : ('');
      }
    }
    return () => {};
  }, []);

  return (
    <div className="min-h-screen bg-gradient-to-b from-[#08115d] to-[#95bf5c]  items-center grid grid-cols-1 place-content-center">
      <Head>
        <title>User Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center ">
        <div>
          <div className="flex justify-center pb-8 pt-2">
            <img className="logo" src="/pikoo-logo.png" />
          </div>
          <div className=" bg-white rounded-lg  shadow-md ">
            <LanDropdown />
          </div>

          <div className="max-w-md w-full sm:w-96  bg-white rounded-lg  shadow-md mb-4 ">
            <h5 className="text-base p-3 font-medium text-gray-900 bg-[#c5f177] text-center rounded-tl-lg rounded-tr-lg shadow-md">
              {`${t("common:Userlogin")}`}
            </h5>

            <div className="sm:pt-0 px-10 sm:px-10 mt-4 md:px-8">
              <form onSubmit={formik.handleSubmit} method="post">
                <div className="">
                  <Inputfield
                    label={`${t("common:login")}`}
                    htmlFor={"email"}
                    name={"email"}
                    id={"email"}
                    inputtype={"email"}
                    placeholder="example@mail.com"
                    onChange={formik.handleChange}
                    value={formik.values.email}
                  />
                  <p className="block h-6 text-xs font-medium text-red-600">
                    {formik.errors.email && formik.touched.email && (
                      <div className="block h-2 text-xs font-medium text-red-600">
                        {formik.errors.email}
                      </div>
                    )}
                  </p>
                  <Inputfield
                    label={`${t("common:password")}`}
                    htmlFor={"password"}
                    name={"password"}
                    id={"password"}
                    type="password"
                    onChange={formik.handleChange}
                    value={formik.values.password}
                  />
                  <p className="block h-4 text-xs font-medium text-red-600">
                    {formik.errors.password && formik.touched.password && (
                      <div className="block h-2 text-xs font-medium text-red-600">
                        {formik.errors.password}
                      </div>
                    )}
                  </p>
                </div>
                <div>
                  <p className="text-center text-sm">
                    {message ? message : ""}
                  </p>
                </div>
                <div className=" sm:px-8 pb-4 items-center text-center">
                  {loading ? (
                    <div role="status" className="flex justify-center">
                      <svg
                        aria-hidden="true"
                        className="mr-2 w-6 h-6 text-gray-200 animate-spin dark:text-gray-600 fill-blue-600"
                        viewBox="0 0 100 101"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z"
                          fill="currentColor"
                        ></path>
                        <path
                          d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z"
                          fill="currentFill"
                        ></path>
                      </svg>
                      <span className="">Processing...</span>
                    </div>
                  ) : (
                    <Btn type="submit" innertext={`${t("common:login")}`} />
                  )}
                  <div className="mt-3 text-center underline text-blue-600">
                    <Link href="/">
                      <a>SignUp</a>
                    </Link>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Login;
