import React, { useState } from "react";
import Head from "next/head";
import PrimaryBtn from "../components/PrimaryBtn";
import DashboardSidebar2 from "../components/DashboardSidebar2";
import DashboardHeader from "../components/DashboardHeader";
import { useTranslation } from "react-i18next";

export default function PaymentDeails(props: any) {
  const { t, i18n } = useTranslation();

  return (
    <div className=" h-full">
      <Head>
        <title>Payment Method</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-no-wrap w-full">
        <DashboardSidebar2 />
        <div className=" bg-gray-50 min-h-screen w-[100%] sm:w-[80%] ">
          <DashboardHeader />
          <div className="px-10 py-6 ">
            <div className="flex justify-between">
              <div className="flex items-center">
                <p className="font-bold">  {`${t("dashboard:paymenthistory")}`}</p>
              </div>
            </div>
          </div>
          <div className=" px-10">
            <div className="container h-full  rounded mb-8">
              <div className="w-full h-full bg-white rounded shadow-md">
                {/* <div className="py-4  "> */}
                <div className="overflow-x-auto relative  sm:rounded-lg">
                  <table className="w-full text-sm text-left text-gray-500 ">
                    <thead className=" text-xs text-gray-700 uppercase  bg-[#c5f177] rounded-t-md">
                      <tr className="">
                        <th
                          scope="col"
                          className="py-4 px-6 flex justify-center"
                        >
                         {t("dashboard:MonthlyScripture")}
                        </th>
                        <th scope="col" className="py-4 px-6">
                        {t("dashboard:DateOfOperation")}
                        </th>
                        <th scope="col" className="py-4 px-6">
                        {t("dashboard:SUM")}
                        </th>
                        <th
                          scope="col"
                          className="py-4 px-6 flex justify-center"
                        >
                             {t("dashboard:DOCUMENT")}
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr className="bg-white border-b ">
                        <th
                          scope="row"
                          className="py-4 px-6 font-medium text-gray-900 whitespace-nowrap flex justify-center"
                        >
                          Master Card ************ 1237
                        </th>
                        <td className="py-4 px-6">21.12.2021 10:07:21</td>
                        <td className="py-4 px-6">540 Euro</td>
                        <td className="py-4 px-6 flex justify-center">
                          <div className="flex cursor-pointer ">
                            <img
                              src="/download-arrow.png"
                              className="w-4"
                              alt=""
                            />
                          </div>
                        </td>
                      </tr>
                      <tr className="bg-gray-50 border-b ">
                        <th
                          scope="row"
                          className="py-4 px-6 font-medium text-gray-900 whitespace-nowrap flex justify-center"
                        >
                          Master Card ************ 1237
                        </th>
                        <td className="py-4 px-6">21.12.2021 10:07:21</td>
                        <td className="py-4 px-6">540 Euro</td>
                        <td className="py-4 px-6 flex justify-center">
                          <div className="flex cursor-pointer ">
                            <img
                              src="/download-arrow.png"
                              className="w-4"
                              alt=""
                            />
                          </div>
                        </td>
                      </tr>
                      <tr className="bg-white border-b">
                        <th
                          scope="row"
                          className="py-4 px-6 font-medium text-gray-900 whitespace-nowrap flex justify-center"
                        >
                          Master Card ************ 1237
                        </th>
                        <td className="py-4 px-6">21.12.2021 10:07:21</td>
                        <td className="py-4 px-6">540 Euro</td>
                        <td className="py-4 px-6 flex justify-center">
                          <div className="flex cursor-pointer ">
                            <img
                              src="/download-arrow.png"
                              className="w-4"
                              alt=""
                            />
                          </div>
                        </td>
                      </tr>
                      <tr className="bg-gray-50 border-b ">
                        <th
                          scope="row"
                          className="py-4 px-6 font-medium text-gray-900 whitespace-nowrap flex justify-center"
                        >
                          Master Card ************ 1237
                        </th>
                        <td className="py-4 px-6">21.12.2021 10:07:21</td>
                        <td className="py-4 px-6">540 Euro</td>
                        <td className="py-4 px-6 flex justify-center">
                          <div className="flex cursor-pointer ">
                            <img
                              src="/download-arrow.png"
                              className="w-4"
                              alt=""
                            />
                          </div>
                        </td>
                      </tr>
                      <tr className="bg-white border-b ">
                        <th
                          scope="row"
                          className="py-4 px-6 font-medium text-gray-900 whitespace-nowrap flex justify-center"
                        >
                          Master Card ************ 1237
                        </th>
                        <td className="py-4 px-6">21.12.2021 10:07:21</td>
                        <td className="py-4 px-6">540 Euro</td>
                        <td className="py-4 px-6 flex justify-center">
                          <div className="flex cursor-pointer ">
                            <img
                              src="/download-arrow.png"
                              className="w-4"
                              alt=""
                            />
                          </div>
                        </td>
                      </tr>
                      <tr className="bg-gray-50 border-b ">
                        <th
                          scope="row"
                          className="py-4 px-6 font-medium text-gray-900 whitespace-nowrap flex justify-center"
                        >
                          Master Card ************ 1237
                        </th>
                        <td className="py-4 px-6">21.12.2021 10:07:21</td>
                        <td className="py-4 px-6">540 Euro</td>
                        <td className="py-4 px-6 flex justify-center">
                          <div className="flex cursor-pointer ">
                            <img
                              src="/download-arrow.png"
                              className="w-4"
                              alt=""
                            />
                          </div>
                        </td>
                      </tr>
                      <tr className="bg-white border-b ">
                        <th
                          scope="row"
                          className="py-4 px-6 font-medium text-gray-900 whitespace-nowrap flex justify-center"
                        >
                          Master Card ************ 1237
                        </th>
                        <td className="py-4 px-6">21.12.2021 10:07:21</td>
                        <td className="py-4 px-6">540 Euro</td>
                        <td className="py-4 px-6 flex justify-center">
                          <div className="flex cursor-pointer ">
                            <img
                              src="/download-arrow.png"
                              className="w-4"
                              alt=""
                            />
                          </div>
                        </td>
                      </tr>
                      <tr className="bg-gray-50 border-b ">
                        <th
                          scope="row"
                          className="py-4 px-6 font-medium text-gray-900 whitespace-nowrap  flex justify-center"
                        >
                          Master Card ************ 1237
                        </th>
                        <td className="py-4 px-6">21.12.2021 10:07:21</td>
                        <td className="py-4 px-6">540 Euro</td>
                        <td className="py-4 px-6 flex justify-center">
                          <div className="flex cursor-pointer ">
                            <img
                              src="/download-arrow.png"
                              className="w-4"
                              alt=""
                            />
                          </div>
                        </td>
                      </tr>
                      <tr className="bg-white border-b ">
                        <th
                          scope="row"
                          className="py-4 px-6 font-medium text-gray-900 whitespace-nowrap  flex justify-center"
                        >
                          Master Card ************ 1237
                        </th>
                        <td className="py-4 px-6">21.12.2021 10:07:21</td>
                        <td className="py-4 px-6">540 Euro</td>
                        <td className="py-4 px-6 flex justify-center">
                          <div className="flex cursor-pointer ">
                            <img
                              src="/download-arrow.png"
                              className="w-4"
                              alt=""
                            />
                          </div>
                        </td>
                      </tr>
                      <tr className="bg-gray-50 border-b ">
                        <th
                          scope="row"
                          className="py-4 px-6 font-medium text-gray-900 whitespace-nowrap  flex justify-center"
                        >
                          Master Card ************ 1237
                        </th>
                        <td className="py-4 px-6">21.12.2021 10:07:21</td>
                        <td className="py-4 px-6">540 Euro</td>
                        <td className="py-4 px-6 flex justify-center">
                          <div className="flex cursor-pointer ">
                            <img
                              src="/download-arrow.png"
                              className="w-4"
                              alt=""
                            />
                          </div>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                  {/* pagination start */}

                  <nav aria-label="Page navigation example">
                    <ul className="py-8 flex items-center justify-center">
                      <li>
                        <a
                          href="#"
                          className="block py-2 px-3 ml-0 leading-tight text-gray-500 bg-white rounded-l-lg  hover:bg-gray-100 hover:text-gray-700 "
                        >
                          {/* <span className="sr-only">Previous</span> */}
                          <svg
                            aria-hidden="true"
                            className="w-5 h-5"
                            fill="currentColor"
                            viewBox="0 0 20 20"
                            xmlns="http://www.w3.org/2000/svg"
                          >
                            <path
                              fillRule="evenodd"
                              d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
                              clipRule="evenodd"
                            ></path>
                          </svg>
                        </a>
                      </li>
                      <li>
                        <a
                          href="#"
                          className="py-2 px-3 leading-tight text-gray-500 bg-white  hover:bg-gray-100 hover:text-gray-700"
                        >
                          1
                        </a>
                      </li>
                      <li>
                        <a
                          href="#"
                          className="py-2 px-3 leading-tight text-gray-500 bg-white  hover:bg-gray-100 hover:text-gray-700"
                        >
                          2
                        </a>
                      </li>
                      <li>
                        <a
                          href="#"
                          aria-current="page"
                          className="z-10 py-2 px-3 leading-tight text-blue-600 bg-blue-50  hover:bg-blue-100 hover:text-blue-700"
                        >
                          3
                        </a>
                      </li>
                      <li>
                        <a
                          href="#"
                          className="py-2 px-3 leading-tight text-gray-500 bg-white hover:bg-gray-100 hover:text-gray-700 "
                        >
                          4
                        </a>
                      </li>
                      <li>
                        <a
                          href="#"
                          className="py-2 px-3 leading-tight text-gray-500 bg-white hover:bg-gray-100 hover:text-gray-700 "
                        >
                          5
                        </a>
                      </li>
                      <li>
                        <a
                          href="#"
                          className="block py-2 px-3 leading-tight text-gray-500 bg-white rounded-r-lg hover:bg-gray-100 hover:text-gray-700 "
                        >
                          {/* <span className="sr-only">Next</span> */}
                          <svg
                            aria-hidden="true"
                            className="w-5 h-5"
                            fill="currentColor"
                            viewBox="0 0 20 20"
                            xmlns="http://www.w3.org/2000/svg"
                          >
                            <path
                              fillRule="evenodd"
                              d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                              clipRule="evenodd"
                            ></path>
                          </svg>
                        </a>
                      </li>
                    </ul>
                  </nav>

                  {/* pagination end */}
                </div>
                {/* </div> */}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
