import React, { useState } from "react";
import Head from "next/head";
import PrimaryBtn from "../components/PrimaryBtn";
import DashboardSidebar2 from "../components/DashboardSidebar2";
import DashboardHeader from "../components/DashboardHeader";
import { useTranslation } from "react-i18next";

export default function PaymentMethod(props: any) {
  const { t, i18n } = useTranslation();

  return (
    <div className=" h-full">
      <Head>
        <title>Payment Method</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-no-wrap w-full">
        <DashboardSidebar2 />
        <div className=" bg-gray-50 min-h-screen w-[100%] sm:w-[80%] ">
          <DashboardHeader />
          <div className="px-10 py-6 ">
            <div className="flex justify-between">
              <div className="flex items-center">
                <p className="font-bold">    {`${t("dashboard:Paymentmethod")}`}
               
                </p>
                
              </div>
            </div>
          </div>
          <div className=" px-10">
            <div className="container h-full  rounded mb-8">
              <div className="w-full h-full bg-white rounded shadow-md">
                <div className="bg-[#c5f177] py-4 px-5 rounded-t-md">
                  <p className="font-bold">Карты</p>
                </div>
                <div className="py-4 px-5 ">
                  <div className=" rounded-lg"><img src="/card.png" className='h-48 w-80' alt="" /></div>
                  <div className="flex my-4">
                    <div><input type="checkbox" /></div>
                    <div className="border-r-2 px-2 border-gray-300"> {t("dashboard:Setasprimary")}</div>
                    <div className="border-r-2 px-2 border-gray-300"> {t("dashboard:Edit")}</div>
                    <div className="px-2 ">{t("dashboard:Delete")}</div>
                  </div>
                <div><div className="text-center border-2 w-80 cursor-pointer hover:shadow-lg rounded-lg border-black p-2 flex justify-center items-center"><div className="mr-2 w-5 h-5 bg-black flex justify-center items-center text-white rounded-full">+</div>{t("dashboard:AddACard")}</div></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
