import React, { useState } from 'react'
import Head from "next/head"
import SecondaryBtn from '../components/SecondaryBtn';
import PrimaryBtn from '../components/PrimaryBtn';
import TriangleBtn from '../components/TriangleBtn';
import DashboardSidebar from '../components/DashboardSidebar';
import Chart from '../components/Chart';
import DashboardHeader from '../components/DashboardHeader';
import { useTranslation } from "react-i18next"

export default function Setting(props: any) {
    const { t, i18n } = useTranslation();
    const [emailEdit, setEmailEdit] = useState(true);
    const [telephoneEdit, setTelephoneEdit] = useState(true);
    const [userNameEdit, setUserNameEdit] = useState(true); 
    const [currentPasswordEdit, setCurrentPasswordEdit] = useState(true);
    const [userName, setUserName] = useState("User Name");
    const [email, setEmail] = useState("testbox@company.com");
    const [telephone, setTelephone] = useState("+3 (096) 000 00 00");
    const [currentPassword, setCurrentPassword] = useState("asdfasdf");

    return (
        <div className=" h-full">
            <Head>
                <title>Dashboard</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex flex-no-wrap w-full">
                <DashboardSidebar />
                <div className=" bg-gray-50 w-[100%] sm:w-[80%] ">
                    <DashboardHeader />
                    <div className='px-10 py-6 '>
                        <div className="flex justify-between">
                            <div className='flex items-center'><p className="font-bold">{t("dashboard:Accountsetup")}</p></div>
                        </div>
                    </div>
                    <div className=' px-10'>

                        <div className="container h-full  rounded mb-8">
                            <div className='w-full h-full bg-white rounded shadow-md'>
                                <div className="bg-[#c5f177] py-4 px-5 rounded-t-md"><p className="font-bold">{t("dashboard:Organizationdata")}</p></div>
                                <div className="py-4 px-5 ">
                                    <div className="flex">
                                        <div>
                                            <p className="px-1 py-2">{t("dashboard:Contactdetails")}</p>
                                            <div className="bg-[#F8F8F8] rounded-lg px-4 py-2 w-80 h-72">
                                                <div>
                                                    <div className="border-b pt-4">
                                                        <p className="text-xs text-gray-300">User Name</p>
                                                        <div className="flex items-center justify-between">
                                                            <input type="text" className={`py-1 text-sm bg-transparent outline-none ${userNameEdit ? 'text-gray-400 ' : ''}`} disabled={userNameEdit} value={userName} onChange={(e) => setUserName(e.target.value)} />
                                                            {userNameEdit ?
                                                                <img className=" h-4 w-4 mr-1 cursor-pointer" src="/edit.png" onClick={() => { setUserNameEdit(!userNameEdit) }} />
                                                                :
                                                                <PrimaryBtn onClick={() => { setUserNameEdit(!userNameEdit) }}>
                                                                    <p className="text-xs">
                                                                        Save
                                                                    </p>
                                                                </PrimaryBtn>}
                                                        </div>
                                                    </div>
                                                    <div className="border-b pt-4">
                                                        <p className="text-xs text-gray-300">Email</p>
                                                        <div className="flex items-center justify-between">
                                                            <input type="email" className={`py-1 text-sm bg-transparent outline-none ${emailEdit ? 'text-gray-400 ' : ''}`} disabled={emailEdit} value={email} onChange={(e) => setEmail(e.target.value)} />
                                                            {emailEdit ?
                                                                <img className=" h-4 w-4 mr-1 cursor-pointer" src="/edit.png" onClick={() => { setEmailEdit(!emailEdit) }} />
                                                                :
                                                                <PrimaryBtn onClick={() => { setEmailEdit(!emailEdit) }}>
                                                                    <p className="text-xs">
                                                                        Save
                                                                    </p>
                                                                </PrimaryBtn>}
                                                        </div>
                                                    </div>
                                                    <div className="border-b pt-4">
                                                        <p className="text-xs text-gray-300">{t("dashboard:Telephone")}</p>
                                                        <div className="flex items-center justify-between">
                                                            <input type="text" className={`py-1 text-sm bg-transparent outline-none ${telephoneEdit ? 'text-gray-400 ' : ''}`} disabled={telephoneEdit} value={telephone} onChange={(e) => setTelephone(e.target.value)} />
                                                            {telephoneEdit ?
                                                                <img className=" h-4 w-4 mr-1 cursor-pointer" src="/edit.png" onClick={() => { setTelephoneEdit(!telephoneEdit) }} />
                                                                :
                                                                <PrimaryBtn onClick={() => { setTelephoneEdit(!telephoneEdit) }}>
                                                                    <p className="text-xs">
                                                                        Save
                                                                    </p>
                                                                </PrimaryBtn>}
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="mr-4 mt-4">
                                        <p className="px-1 py-2">{t("dashboard:Safety")}</p>
                                        <div className="bg-[#F8F8F8] rounded-lg px-4 py-2 w-96 ">
                                            <div>

                                                <div className="border-b pt-4 mb-8">
                                                    <p className="text-xs text-gray-300">{t("dashboard:CurrentPassword")}</p>
                                                    <div className="flex items-center justify-between">
                                                        <input type={currentPasswordEdit ? 'password' : 'text'} className={`py-1 text-sm bg-transparent outline-none ${currentPasswordEdit ? 'text-gray-400 ' : ''}`} disabled={currentPasswordEdit} value={currentPassword} onChange={(e) => setCurrentPassword(e.target.value)} />
                                                        {currentPasswordEdit ?
                                                            <img className=" h-4 w-4 mr-1 cursor-pointer" src="/edit.png" onClick={() => { setCurrentPasswordEdit(!currentPasswordEdit) }} />
                                                            :
                                                            <PrimaryBtn onClick={() => { setCurrentPasswordEdit(!currentPasswordEdit) }}>
                                                                <p className="text-xs">
                                                                    Save
                                                                </p>
                                                            </PrimaryBtn>}
                                                    </div>
                                                </div>
                                                <PrimaryBtn>
                                                    <p className="text-xs">
                                                    {t("dashboard:Changepassword")}
                                                       
                                                    </p>
                                                </PrimaryBtn>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    )
}
